### ISSUE TITLE
Support cash withdrawal transaction

### ISSUE THREAD

**Issue by rlan** [rlan/convert-csv-schwab2pp#2]
A "Wire Received" transaction is currently supported. I don't have an actual wire withdrawal transaction.

**Comment by ipaulo** [comment]
Sample:

"01/01/2024","Wire Sent","","WIRED FUNDS DISBURSED","","","","-$100.00"

**Comment by rlan** [comment]
@ipaulo Thank you for sharing the transaction data. I will update the code.
